/** @type {import('next').NextConfig} */
const nextConfig = {
  env: {
    NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY:
      "pk_test_ZmFpci13b2xmLTU4LmNsZXJrLmFjY291bnRzLmRldiQ",
    CLERK_SECRET_KEY: "sk_test_w7EYU9tiPfQkVmzf8p5xp0DIT0pT2Dy2Ml2BKSC5SZ",
    NEXT_PUBLIC_CLERK_SIGN_IN_URL: "/sign-in",
    NEXT_PUBLIC_CLERK_SIGN_UP_URL: "/sign-up",
    NEXT_PUBLIC_CLERK_SIGN_UP_FORCE_REDIRECT_URL: "/wizard",
    NEXT_PUBLIC_CLERK_SIGN_IN_FORCE_REDIRECT_URL: "/",
    DATABASE_URL:
      "prisma+postgres://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiODA1Y2UwM2UtYTVkMi00YjhiLThiZjItYmYwZDViZGQ0NmY0IiwidGVuYW50X2lkIjoiY2MwYWRiNGIzMzliZGZkNGZhNjU0MjQwYWVlOTYxM2YwMTcyM2FhZjU0NmZlMjhkNDg1NGZiYWEzYmY3MGZjZiIsImludGVybmFsX3NlY3JldCI6ImExMjU3MzVhLWI5YjItNGQ0YS1iOWRkLWVmNmY1YTM5M2U1MSJ9.1hbFZSqDP5YG0pIX9WG-0SkM8QILhABPGKowx5HAG_E",
    PULSE_API_KEY:
      "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiODA1Y2UwM2UtYTVkMi00YjhiLThiZjItYmYwZDViZGQ0NmY0IiwidGVuYW50X2lkIjoiY2MwYWRiNGIzMzliZGZkNGZhNjU0MjQwYWVlOTYxM2YwMTcyM2FhZjU0NmZlMjhkNDg1NGZiYWEzYmY3MGZjZiIsImludGVybmFsX3NlY3JldCI6ImExMjU3MzVhLWI5YjItNGQ0YS1iOWRkLWVmNmY1YTM5M2U1MSJ9.1hbFZSqDP5YG0pIX9WG-0SkM8QILhABPGKowx5HAG_E",
  },
};

export default nextConfig;
